/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cement_stlreader_reader_NativeRenderer */

#ifndef _Included_com_cement_stlreader_reader_NativeRenderer
#define _Included_com_cement_stlreader_reader_NativeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    setZoomRatio
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_setZoomRatio
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    setTransDistX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_setTransDistX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    setTransDistY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_setTransDistY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    setRotateAngleX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_setRotateAngleX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    setRotateAngleY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_setRotateAngleY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    setDobleDown
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_setDobleDown
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    drawStlModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_drawStlModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    surfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_surfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_surfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cement_stlreader_reader_NativeRenderer
 * Method:    surfaceDrawing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cement_stlreader_reader_NativeRenderer_surfaceDrawing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
